# Generated by Django 5.2.8 on 2025-11-26 20:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Receita')),
                ('yield_unit', models.CharField(choices=[('unidades', 'Unidades'), ('quilo', 'Quilo')], max_length=10, verbose_name='Unidade de Rendimento')),
                ('yield_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Rendimento')),
                ('preparation_time', models.PositiveIntegerField(verbose_name='Tempo de Preparo (minutos)')),
                ('final_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Final da Receita')),
            ],
            options={
                'verbose_name': 'Receita Pronta',
                'verbose_name_plural': 'Receitas Prontas',
            },
        ),
        migrations.CreateModel(
            name='FixedCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=120)),
                ('valores', models.JSONField(blank=True, default=dict, help_text='Valores flexíveis em JSON')),
                ('valor_medio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Produto')),
                ('qtt_input', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Quantidade do Insumo')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Custo Unitário')),
                ('unit_of_measurement', models.CharField(choices=[('litro', 'Litro'), ('unidade', 'Unidade'), ('quilo', 'Quilo'), ('metro', 'Metro')], max_length=25, verbose_name='Unidade de Medida')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Ultima Atualização')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProLabore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(default='Pró-labore', max_length=120)),
                ('valor_mensal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'verbose_name': 'Pró-labore',
                'verbose_name_plural': 'Pró-labores',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'create'), ('update', 'update'), ('delete', 'delete')], max_length=10)),
                ('model_name', models.CharField(max_length=120)),
                ('object_repr', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=80)),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('tema_projeto', models.CharField(max_length=80)),
                ('nome_precificacao', models.CharField(default='', max_length=120)),
                ('produtos', models.JSONField(blank=True, default=list)),
                ('tempo_preparo', models.IntegerField(default=0, help_text='Tempo em minutos')),
                ('rendimento', models.CharField(blank=True, default='', max_length=80)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pricings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantidade')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.input')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.finishedrecipe')),
            ],
            options={
                'verbose_name': 'Ingrediente da Receita',
                'verbose_name_plural': 'Ingredientes da Receita',
                'unique_together': {('recipe', 'ingredient')},
            },
        ),
        migrations.AddField(
            model_name='finishedrecipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='app.RecipeIngredient', to='app.input', verbose_name='Ingredientes'),
        ),
    ]
