# Generated by Django 5.2.8 on 2025-11-18 00:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=120)),
                ('valores', models.JSONField(blank=True, default=dict, help_text='Valores flexíveis em JSON')),
                ('valor_medio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='ProLabore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(default='Pró-labore', max_length=120)),
                ('valor_mensal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'create'), ('update', 'update'), ('delete', 'delete')], max_length=10)),
                ('model_name', models.CharField(max_length=120)),
                ('object_repr', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=80)),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('tema_projeto', models.CharField(max_length=80)),
                ('nome_precificacao', models.CharField(default='', max_length=120)),
                ('produtos', models.JSONField(blank=True, default=list)),
                ('tempo_preparo', models.IntegerField(default=0, help_text='Tempo em minutos')),
                ('rendimento', models.CharField(blank=True, default='', max_length=80)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pricings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
